### PR TITLE
Manage renamed files in PR diff

### PR DESCRIPTION
**Pull request by GuillaumeLagrange**
If a file was renamed during the PR, its diff view would be useless because the plugin would try to `git show` the new file name on the base ref, when it did not exist.

I tested it in file diff view, not sure about commit by commit review since I use this feature much less than the whole file change

### CODE REVIEW

**Comment by ldelossa** [comment]
Hey there, should the editorconfig file be included?

**Comment by ldelossa** [comment]
> tested it in file diff view, not sure about commit by commit review since I use this feature much less than the whole file change

mind doing a small test just to ensure commit by commit review works? It should since the code is shared

**Comment by GuillaumeLagrange** [comment]
I added the editorconfig so that other future contributors dont have to bother with it since it's quite standard.
If you wish I can keep it local only, it's really up to you :)

I tested with a commit by commit and it seems to work fine !
Do you want me to create a minimal repro repo with an example PR so you can play around with it ?

**Comment by GuillaumeLagrange** [comment]
Here you go if you want to play around: https://github.com/GuillaumeLagrange/neoconf-repro/pull/1
It seems coherent to me :hugs:

**Comment by ldelossa** [comment]
Testing it out seems fine. 

Lua formatting im torn on. Lately ive just been using what ever the default null-ls language server, will editorconfig file get picked up by that?

**Comment by GuillaumeLagrange** [comment]
It should not conflict as far as I know, but don't worry I'll just remove it and keep it local

**Comment by ldelossa** [comment]
Thanks. And thanks for the PR.

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
